# Generated by Django 4.2.16 on 2024-11-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(default='', max_length=50, verbose_name='Telegram Username'),
        ),
    ]
