# Generated by Django 4.2.16 on 2024-11-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_del_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
